In [2]:
import numpy as np
#одномерный массив
numbers = np.array([1, 2, 3, 4, 5, 6, 8, 9])
print("одномерный массив")
print(numbers, numbers.shape, numbers.dtype)
#массив, заполненный нулями
zero_matrix = np.zeros((3, 3))
print("матрица")
print(zero_matrix)
#массив чисел от 0 до 9
range_array = np.arange(10)
print("массив")
print(range_array)
#доступ к элементам массива
first_element = numbers[0]
print("первый элемент" ,first_element)
#двумерный массив
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60], 
    [70, 80, 90]
])
element = matrix[1, 2]
print("найденный элемент", element)
#математические операции
sum1 = np.sum(numbers)
print("сумма элементов массива", sum1)
matrix2 = np.mean(matrix)
print("среднее значение матрицы", matrix2)
#поэлементные операции
doub = numbers * 2
print("массив, умноженный на 2")
print(doub)

одномерный массив
[1 2 3 4 5 6 8 9] (8,) int64
матрица
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
массив
[0 1 2 3 4 5 6 7 8 9]
первый элемент 1
найденный элемент 60
сумма элементов массива 38
среднее значение матрицы 50.0
массив, умноженный на 2
[ 2  4  6  8 10 12 16 18]
